import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import "../styles/globals.scss";
//ANCHOR - project components
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer-Section/Footer";

const playpen = Playpen_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playpen.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
