import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "../styles/globals.scss";

//import 'bootstrap/dist/css/bootstrap.min.css';
//import '@fortawesome/fontawesome-free/css/all.min.css';

import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;


const playpen = Playpen_Sans({ subsets: ["latin"] });

//ANCHOR - project components
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer-Section/Footer";

export const metadata: Metadata = {
  title: "Pet Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playpen.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}















// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { Playpen_Sans } from "next/font/google";

// const PlaypenSans = Playpen_Sans({ subsets: ["latin"] });


// import "../styles/globals.scss";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
