import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "../styles/globals.scss";
import 'bootstrap/dist/css/bootstrap.min.css';

const PlaypenSans = Playpen_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pet Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PlaypenSans.className}>
        {children}
      </body>
    </html>
  );
}















// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { Playpen_Sans } from "next/font/google";

// const PlaypenSans = Playpen_Sans({ subsets: ["latin"] });


// import "../styles/globals.scss";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
